name: validate-dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:
  workflow_run:
    workflows: ["update-readme"]
    types:
      - completed

jobs:
  update-version:
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch')
    
    runs-on: self-hosted 
    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Incrementar AppVersion y Fecha en el README
        shell: powershell
        run: |
          $Ahora = [DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ss") + " UTC"
          
          $Path = "README.md"
          
          $Content = Get-Content -Path $Path -Raw
          
          $Pattern = "(?m)^AppVersion-(\d+).*"
          
          if ($Content -match $Pattern) {
              $VersionVieja = [int]$Matches[1]
              $VersionNueva = $VersionVieja + 1
              
              Write-Host "Actualizando de versión $VersionVieja a versión $VersionNueva"
              
              $NuevoTexto = "AppVersion-$VersionNueva (Actualizado: $Ahora)"
              $Content = $Content -replace $Pattern, $NuevoTexto
              
              [System.IO.File]::WriteAllText($Path, $Content, [System.Text.Encoding]::UTF8)
          } else {
              Write-Warning "⚠️ No se encontró la estructura 'AppVersion-X'. Inicializando al final del archivo..."
              Add-Content -Path $Path -Value "`nAppVersion-1 (Actualizado: $Ahora)"
          }

      - name: Confirmar y subir cambios
        shell: powershell
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          
          $diff = git diff --quiet
          $diffStaged = git diff --staged --quiet
          
          if ($LASTEXITCODE -ne 0) {
              git commit -m "build: incrementar AppVersion e historial de tiempo [skip ci]"
              git push origin main
          } else {
              Write-Host "No hay cambios detectados en el README.md."
          }